import { Item, Recipe, Substitution } from '../types';

export const INITIAL_ITEMS: Partial<Item>[] = [
  {nome:"Seleta de frutas",categoria:"Fruta",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Banana",categoria:"Fruta",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Pão Francês com queijo",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Muffins de banana e coco",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Muffins de banana e coco sem ovo",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Panini",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Macaxeira com ovos",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:false},
  {nome:"Macaxeira com carne",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Pão assado com requeijão",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Panqueca americana com calda de cacau",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Panqueca sem ovo com calda de cacau",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Bolo de iogurte natural",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Bolo simples sem ovo",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Tapioca de queijo e coco",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:false},
  {nome:"Tapioca de queijo",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:false},
  {nome:"Tapioca",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Biscoito crocante de aveia e chocolate",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Biscoito aveia sem ovo",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Pão de queijo",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:false},
  {nome:"Bolo mesclado de cenoura",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Bolo mesclado sem ovo",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Toast com banana e calda de cacau",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Torrada com calda de cacau",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Cuscuz com ovos",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:false},
  {nome:"Cuscuz com requeijão",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:false},
  {nome:"Açaí com leite pó e granola",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Biscoito caseiro",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Biscoito caseiro sem ovo",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Biscoito caseiro de banana",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Pão delícia",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Esfirra saudável",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Brownie de batata doce",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:false},
  {nome:"Batata doce com frango",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Mini cachorro quente",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Bolo bacia",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Bolo bacia sem ovo",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Bolo de laranja",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Bolo simples",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Pãozinho de batata doce com chia",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Inhame com carne",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Inhame com frango",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Leite pó, Granola, Aveia",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Banana comprida grelhada com canela",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:false},
  {nome:"Creme de legumes com torrada",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Bolo de frutas",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Pastelzinho de carne com legumes",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Bolo Prestígio",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Pão sedinha com queijo",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Coxinha de forno",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Mini pizza",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Bolo de fubá",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:false},
  {nome:"Cuca de banana",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Mini Broa",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Cookie de cacau",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:true},
  {nome:"Queijo quente",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Sopa creme de legumes com torrada",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Brioche com queijo",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Cereal",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Biscoito de banana",categoria:"Lanche",contemOvo:false,contemLactose:false,contemGluten:true},
  {nome:"Waffle com calda de cacau",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Enroladinho de pão",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Crepinho com sorvete caseiro",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Pãozinho recheado",categoria:"Lanche",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Torradinha com pasta Ricota e tomate",categoria:"Lanche",contemOvo:false,contemLactose:true,contemGluten:true},
  {nome:"Biscoito Polvilho Caseiro",categoria:"Lanche",contemOvo:true,contemLactose:false,contemGluten:false},
  {nome:"Suco de uva",categoria:"Suco"},
  {nome:"Suco de cajá",categoria:"Suco"},
  {nome:"Suco de maracujá",categoria:"Suco"},
  {nome:"Suco de acerola com cenoura",categoria:"Suco"},
  {nome:"Suco de caju",categoria:"Suco"},
  {nome:"Suco de tangerina",categoria:"Suco"},
  {nome:"Suco de goiaba",categoria:"Suco"},
  {nome:"Suco de graviola",categoria:"Suco"},
  {nome:"Suco de morango com abacaxi",categoria:"Suco"},
  {nome:"Suco misto",categoria:"Suco"},
  {nome:"Suco de manga com laranja",categoria:"Suco"},
  {nome:"Suco de acerola",categoria:"Suco"},
  {nome:"Suco de abacaxi com maçã",categoria:"Suco"},
  {nome:"Suco de pitanga",categoria:"Suco"},
  {nome:"Suco de goiaba com limão",categoria:"Suco"},
  {nome:"Suco de laranja com mamão",categoria:"Suco"},
  {nome:"Suco de tangerina com mamão",categoria:"Suco"},
  {nome:"Suco de morango",categoria:"Suco"},
  {nome:"Suco de manga",categoria:"Suco"},
  {nome:"Suco de abacaxi",categoria:"Suco"},
  {nome:"Suco de acerola com laranja",categoria:"Suco"},
  {nome:"Água de coco",categoria:"Bebida"},
  {nome:"Iogurte",categoria:"Bebida",contemLactose:true},
  {nome:"Leite fermentado",categoria:"Bebida",contemLactose:true},
  {nome:"Torradinha com geleia",categoria:"Opção Semana"},
  {nome:"Torrada com geleia",categoria:"Opção Semana"},
  {nome:"Pão catita com requeijão",categoria:"Opção Semana",contemLactose:true},
  {nome:"Cenoura ralada",categoria:"Entrada"},
  {nome:"Brócolis",categoria:"Entrada"},
  {nome:"Manga",categoria:"Entrada"},
  {nome:"Ovo de codorna",categoria:"Entrada",contemOvo:true},
  {nome:"Abacaxi",categoria:"Entrada"},
  {nome:"Milho",categoria:"Entrada"},
  {nome:"Ervilhas",categoria:"Entrada"},
  {nome:"Beterraba cozida",categoria:"Entrada"},
  {nome:"Jerimum",categoria:"Entrada"},
  {nome:"Ovos cozidos",categoria:"Entrada",contemOvo:true},
  {nome:"Cenoura cozida",categoria:"Entrada"},
  {nome:"Abobrinha",categoria:"Entrada"},
  {nome:"Salada mista",categoria:"Entrada"},
  {nome:"Repolho refogado",categoria:"Entrada"},
  {nome:"Vinagrete de manga",categoria:"Entrada"},
  {nome:"Legumes do cozido",categoria:"Entrada"},
  {nome:"Filé de frango molho de queijo",categoria:"Prato Principal",contemLactose:true,contemGluten:true},
  {nome:"Picadinho de carne com batatas",categoria:"Prato Principal"},
  {nome:"Filé de peixe agridoce",categoria:"Prato Principal",contemGluten:true},
  {nome:"Bife ao molho de estrogonofe",categoria:"Prato Principal",contemLactose:true,contemGluten:true},
  {nome:"Frango assado a Jardineira",categoria:"Prato Principal"},
  {nome:"Carne moída",categoria:"Prato Principal"},
  {nome:"Filé de frango com brócolis",categoria:"Prato Principal"},
  {nome:"Bife à cavalo",categoria:"Prato Principal",contemOvo:true},
  {nome:"Carne de sol com queijo",categoria:"Prato Principal",contemLactose:true},
  {nome:"Coxinha de frango assada",categoria:"Prato Principal",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Iscas de peixe com molho iogurte",categoria:"Prato Principal",contemLactose:true,contemGluten:true},
  {nome:"Bife caseiro com batatas",categoria:"Prato Principal"},
  {nome:"Filé de frango à Parmegiana",categoria:"Prato Principal",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Cozido",categoria:"Prato Principal"},
  {nome:"Filezinho de frango crocante",categoria:"Prato Principal",contemOvo:true,contemGluten:true},
  {nome:"Panqueca de carne com queijo",categoria:"Prato Principal",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Filé de peixe com molho maracujá",categoria:"Prato Principal",contemGluten:true},
  {nome:"Carne assada",categoria:"Prato Principal"},
  {nome:"Frango guisado com batatas",categoria:"Prato Principal"},
  {nome:"Lasanha",categoria:"Prato Principal",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Filé de frango com abacaxi grelhado",categoria:"Prato Principal"},
  {nome:"Arroz/Feijão mulatinho/Purê/Batata palha",categoria:"Acompanhamento"},
  {nome:"Arroz/Feijão preto/Purê/Espaguete",categoria:"Acompanhamento",contemGluten:true},
  {nome:"Arroz/Feijão mulatinho/Purê/Batatas douradas",categoria:"Acompanhamento"},
  {nome:"Arroz/Feijão preto/Purê/Omelete de legumes",categoria:"Acompanhamento",contemOvo:true},
  {nome:"Arroz/Feijão mulatinho/Purê/Farofa",categoria:"Acompanhamento"},
  {nome:"Arroz/Feijão preto/Purê/Macarrão letrinha",categoria:"Acompanhamento",contemGluten:true},
  {nome:"Arroz/Feijão mulatinho/Purê/Macaxeira palito",categoria:"Acompanhamento"},
  {nome:"Arroz/Feijão preto/Purê/Pirão",categoria:"Acompanhamento",contemGluten:true},
  {nome:"Arroz/Feijão preto/Purê/Quiche de legumes",categoria:"Acompanhamento",contemOvo:true,contemLactose:true,contemGluten:true},
  {nome:"Arroz/Feijão mulatinho/Purê/Penne molho queijo",categoria:"Acompanhamento",contemLactose:true,contemGluten:true},
  {nome:"Arroz/Feijão preto/Purê/Souflê de milho",categoria:"Acompanhamento",contemOvo:true,contemLactose:true},
  {nome:"Sopa de carne com macarrão",categoria:"Ceia",contemGluten:true},
  {nome:"Cuscuz com carne picadinha",categoria:"Ceia"},
  {nome:"Inhame com frango (ceia)",categoria:"Ceia"},
  {nome:"Sopa de feijão",categoria:"Ceia"},
  {nome:"Macarronada",categoria:"Ceia",contemLactose:true,contemGluten:true},
  {nome:"Macaxeira com frango",categoria:"Ceia"},
  {nome:"Canja",categoria:"Ceia"},
  {nome:"Batata doce com carne",categoria:"Ceia"},
  {nome:"Tapioca com carne desfiada",categoria:"Ceia"},
  {nome:"Sopa creme de legumes (ceia)",categoria:"Ceia",contemLactose:true},
  {nome:"Inhame com requeijão",categoria:"Ceia",contemLactose:true},
  {nome:"Polenta com frango",categoria:"Ceia"},
  {nome:"Batata doce com frango de molho",categoria:"Ceia"},
  {nome:"Macaxeira com carne de molho",categoria:"Ceia"},
  {nome:"Sopa de legumes com carne",categoria:"Ceia"},
  {nome:"Cuscuz com frango",categoria:"Ceia"},
  {nome:"Inhame com carne (ceia)",categoria:"Ceia"}
];

export const INITIAL_RECIPES: Partial<Recipe>[] = [
  {nome:"Biscoito crocante de aveia e cacau",ingredientes:"1/4 xíc. água quente, 3-4 col. sopa açúcar mascavo, 1 col. sopa cacau em pó, 2 col. sopa manteiga, 1 1/3 xíc. farinha de aveia, 1 col. chá fermento em pó",modoPreparo:"Misturar água, açúcar, cacau e manteiga. Acrescentar farinha e fermento. Sovar. Abrir com rolo, cortar. Assar 180°C 20-25min.",porcoes:30},
  {nome:"Bolo Prestígio",ingredientes:"1 ovo, 1 col. óleo, 1 col. leite desnatado, 2 col. açúcar mascavo, 2 col. farinha aveia, 2 col. polvilho doce, 1 col. cacau, fermento. Cobertura: leite, cacau, amido, açúcar, coco ralado",modoPreparo:"Misturar massa. Assar 180°C ~20min. Cobertura: misturar em panela até engrossar. Cobrir bolo e finalizar com coco.",porcoes:30},
  {nome:"Muffins de banana e coco",ingredientes:"250ml leite amêndoa, 6 ovos, 10 col. coco ralado, 20 col. flocos aveia, 10 col. polvilho, 5 col. farelo aveia, fermento, gotas chocolate",modoPreparo:"Misturar tudo (menos fermento). Descansar 20min. Adicionar fermento. Despejar em forma. Assar 180°C.",porcoes:30}
];
